// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "gui.h"

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(250, 200, "FLTK Demo");
    w = o; if (w) {/* empty */}
    o->end();
  } // Fl_Double_Window* o
  return w;
}
